name: train_wan1b_teacher_shift5_81f_480p_lr5e-5_6k_b32
mode: train
manual_seed: 0
mixed_precision: true

# dataset and data loader settings
datasets:
  train:
    type: T2VTarDataset
    meta_path: assets/data/meta/vidprom_dummy/raw.json
    num_frames: 81
    data_dtype: .mp4
    dataloader_cfg:
      batch_size_per_gpu: 2
      num_workers: 8
      shuffle_chunk_size: 1000
      drop_last: true

  # val:
  #   type: VBenchT2VDataset
  #   num_samples_per_prompt: 5
  #   dataloader_cfg:
  #     batch_size_per_gpu: 1

  sample:
    type: PromptDataset
    prompt_path: assets/evaluation/eval_caption_t2v.json
    preprocess_cfg:
      height: 480
      width: 832
    dataloader_cfg:
      batch_size_per_gpu: 1

models:
  transformer_cfg:
    model_name: experiments/pretrained_models/Wan2.1-T2V-1.3B-Diffusers
    model_type: FAR_Wan_Transformer3DModel
    enable_gradient_checkpoint: true
    lora_config:
      lora_rank: 256
      lora_alpha: 256
      target_module_name: ["attn1.to_q", "attn1.to_k", "attn1.to_v", "attn1.to_out.0", "ffn.net.0.proj", "ffn.net.2"]
    param_names_to_optimize: ["lora_A", "lora_B"]
    i2v_prob: 0
  text_encoder_cfg:
    drop_text_ratio: 0.1
    negative_embedding_path: assets/negative_embedding/wan_negemb_cn.pth
  vae_cfg:
    load: true
  scheduler_cfg:
    shift: 5.0

# path
path:
  pretrain_network: ~

# training settings
train:
  train_pipeline: WanTeacherTrainer

  optim_g:
    type: AdamW
    lr: !!float 5e-5
    weight_decay: !!float 0
    betas: [0.9, 0.95]

  ema_decay: 0.999
  ema_warmup_step: 1000

  lr_scheduler: constant_with_warmup

  warmup_iter: 1000
  total_iter: 6000
  max_grad_norm: 1.0

# validation settings
val:
  val_pipeline: WanAnyFlowPipeline
  skip_first_eval: true
  sample_freq: 1000
  eval_freq: 1000
  sample_cfg:
    height: 480
    width: 832
    seed: [0, 1]
    guidance_scale: 3.0
    num_inference_steps: [24]
    num_vbench_inference_steps: 50
    num_frames: 81
    negative_prompt: "色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走"
  eval_cfg:
    vbench: ~

# logging settings
logger:
  print_freq: 1
  save_checkpoint_freq: 50
  save_eval_checkpoint_freq: 2000
  use_wandb: false
